// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WSRoom } from "./WSRoom";
import type { WSUserMessage } from "./WSUserMessage";

export type EventFromServer = { "type": "SyncMessage" } & Array<WSUserMessage> | { "type": "Message" } & WSUserMessage | { "type": "JoinedRoom" } & WSRoom | { "type": "FailedToJoinRoom", message: string, } | { "type": "AddReaction" };
