// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FailedToJoinRoomReason } from "./FailedToJoinRoomReason";
import type { WSRoom } from "./WSRoom";
import type { WSUserMessageFromServer } from "./WSUserMessageFromServer";

export type EventFromServer = { "type": "SyncMessage", messages: Array<WSUserMessageFromServer>, } | { "type": "Message" } & WSUserMessageFromServer | { "type": "JoinedRoom" } & WSRoom | { "type": "FailedToJoinRoom", reason: FailedToJoinRoomReason, } | { "type": "AddReaction" };
