// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WSUserMessage } from "./WSUserMessage";

export type EventFromClient = { "type": "RequestSyncMessage", limit: number, } | { "type": "UserMessage" } & WSUserMessage | { "type": "JoinRoom", token: string, } | { "type": "AddReaction" };
