// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FailedToJoinRoomReason = { "type": "Unauthorized" } | { "type": "RoomNotFound" } | { "type": "NotParticipated", room_id: string, } | { "type": "InternalError" };
