// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WSUserMessage = { author_id: string, author_name: string, author_avatar_url: string, content: string, reply_to_id: string | null, };
