version: '3'
silent: true

dotenv:
  - ".env"

# docker-compose派とdocker compose派のどちらにも対応する
vars:
  DOPPLER_CMD:
    sh: |
      if command -v doppler >/dev/null 2>&1; then
        echo "doppler run --"
      else
        echo ""
      fi
  COMPOSE_CMD:
    sh: |
      if command -v docker compose >/dev/null 2>&1; then
        echo "docker compose"
      elif command -v docker-compose >/dev/null 2>&1; then
        echo "docker-compose"
      else
        echo "docker compose"
      fi

includes:
  web:
    dir: ./web
    taskfile: ./taskfile/Taskfile.web.yml

  core:
    dir: ./core
    taskfile: ./taskfile/Taskfile.core.yml

  db:
    dir: ./db
    taskfile: ./taskfile/Taskfile.db.yml
    flatten: true

tasks:
  default:
    desc: List all tasks
    aliases:
      - list
    cmd: task -l

  up:
    desc: Up docker
    cmds:
     - "{{.DOPPLER_CMD}} {{.COMPOSE_CMD}} up -d"

  down:
    desc: Down docker
    cmd: "{{.DOPPLER_CMD}} {{.COMPOSE_CMD}} down"

  test:
    deps:
      - task: core:test

  dev:
    desc: Start web and core server
    deps:
      - task: web:dev
      - task: core:dev

  add:
    deps:
      - task: web:add

  remove:
    deps:
      - task: web:remove

  install:
    desc: Install dependencies
    deps:
      - task: web:install

  ngrok:
    desc: Start ngrok tunnel
    cmd: ngrok http --domain={{.NGROK_DOMAIN}} 3050
  
  nvim:
    desc: Nvim with env
    cmd: "{{.DOPPLER_CMD}} nvim"

  zodios-gen:
    desc: Generate API
    cmd: pnpm openapi-zod-client http://localhost:3050/api-docs/openapi.json -o src/zodios/api.ts 
