[workspace]
members = ["chat", "db", "models"]
default-members = ["chat"]

[workspace.package]
name = "occha-core"
authors = ["Occha Dev"]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
chrono = "0.4.39"
tokio = "1.43.0"
thiserror = "2.0.11"
