// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WSUserMessageFromServer = { id: string, author_id: string | null, author_name: string | null, author_avatar_url: string, content: string, reply_to_id: string | null, };
