[package]
name = "models"
version.workspace = true
edition.workspace = true

[dependencies]
sqlx = { version = "0.8.3", features = ["chrono"] }
serde = { version = "1.0.217", features = ["derive"] }
chrono = { workspace = true, features = ["serde"] }
clerk-rs = "0.4.0"
